#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : re2
Version  : 2019.03.01
Release  : 1
URL      : https://github.com/google/re2/archive/2019-03-01.tar.gz
Source0  : https://github.com/google/re2/archive/2019-03-01.tar.gz
Summary  : RE2 is a fast, safe, thread-friendly regular expression engine.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: re2-lib = %{version}-%{release}
Requires: re2-license = %{version}-%{release}
BuildRequires : buildreq-cmake

%description
This is the source code repository for RE2, a regular expression library.
For documentation about how to install and use RE2,
visit https://github.com/google/re2/.

%package dev
Summary: dev components for the re2 package.
Group: Development
Requires: re2-lib = %{version}-%{release}
Provides: re2-devel = %{version}-%{release}

%description dev
dev components for the re2 package.


%package lib
Summary: lib components for the re2 package.
Group: Libraries
Requires: re2-license = %{version}-%{release}

%description lib
lib components for the re2 package.


%package license
Summary: license components for the re2 package.
Group: Default

%description license
license components for the re2 package.


%prep
%setup -q -n re2-2019-03-01

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552718003
export LDFLAGS="${LDFLAGS} -fno-lto"
make  %{?_smp_mflags} includeir=/usr/include libdir=/usr/lib64


%install
export SOURCE_DATE_EPOCH=1552718003
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/re2
cp LICENSE %{buildroot}/usr/share/package-licenses/re2/LICENSE
%make_install includeir=/usr/include libdir=/usr/lib64

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/lib64/libre2.so
/usr/lib64/pkgconfig/re2.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libre2.so.0
/usr/lib64/libre2.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/re2/LICENSE
